apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: terraform-provider-rhcs2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: terraform-provider-rhcs2
    app.kubernetes.io/part-of: terraform-provider-rhcs-test
  name: terraform-provider-rhcs24ayv
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: terraform-provider-rhcs2
    weight: 100
status: {}
